import { Injectable } from '@nestjs/common';
import { ApolloError } from 'apollo-server-express';
import { PlayerRepository } from '../repositories/player.repository';
import { PlayerArgs } from '../dto/player.args';
import { PlayerEntity } from '../entities/player.entity';
import { getConnection } from 'typeorm';
import { UserRepository } from '../../users/repositories/users.repository';
import { PlayerNftEntity } from '../../player-nft/entities/player-nft.entity';
import { ClubRepository } from 'src/modules/club/repositories/club.repository';

@Injectable()
export class PlayerService {
  constructor(
    private readonly userRepository: UserRepository,
    private readonly playerRepository: PlayerRepository,
    private readonly clubRepository: ClubRepository,
  ) {}

  async findOne(id: string) {
    try {
      return await this.playerRepository.findOne(id, {
        relations: ['club', 'events'],
      });
    } catch (error) {
      console.log('error', error);
      throw new ApolloError('Get Player Fail', 'get_player_failed');
    }
  }

  async findOneByWallet(walletAddress: string, id: string) {
    try {
      const data = await this.playerRepository
        .createQueryBuilder('player')
        .leftJoinAndSelect('player.nft', 'nft')
        .where('player.id = :id', { id })
        .where('nft.walletAddress = :walletAddress', { walletAddress })
        .getOne();

      return data;
    } catch (error) {
      console.log('error', error);
      throw new ApolloError('Get Player Fail', 'get_player_failed');
    }
  }

  async findByWallet(walletAddress: string) {
    try {
      const data = await this.playerRepository
        .createQueryBuilder('player')
        .leftJoinAndSelect(PlayerNftEntity, 'nft', 'player.id = nft.playerId')
        .where('nft.walletAddress = :walletAddress', { walletAddress })
        .getMany();
      return data;
    } catch (error) {
      console.log('error', error);
      throw new ApolloError('Get Player Fail', 'get_player_failed');
    }
  }

  async pagination({ page, limit, filters }: PlayerArgs) {
    return this.playerRepository.paginate(
      {
        page,
        limit,
        filters,
      },
      {
        order: {
          createdAt: 'DESC',
        },
      },
    );
  }

  async generatePlayer() {
    const players: any[] = [
      // // Arsenal
      // {
      //   rewardCode: 1,
      //   playerId: '',
      //   clubId: '1',
      //   contestantId: '',
      //   firstName: 'Gabriel',
      //   lastName: 'Jesus',
      //   shortFirstName: 'Gabriel',
      //   shortLastName: 'Jesus',
      //   shirtPlayer: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p205651.png',
      //   matchName: '',
      //   shirtNumber: '9',
      //   position: 'Forward',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 2,
      //   playerId: '',
      //   clubId: '1',
      //   contestantId: '',
      //   firstName: 'Gabriel',
      //   lastName: '',
      //   shortFirstName: 'Gabriel',
      //   shortLastName: '',
      //   shirtPlayer: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p226597.png',
      //   matchName: '',
      //   shirtNumber: '6',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 3,
      //   playerId: '',
      //   clubId: '1',
      //   contestantId: '',
      //   firstName: 'Saka',
      //   lastName: '',
      //   shortFirstName: 'Saka',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 4,
      //   playerId: '',
      //   clubId: '1',
      //   contestantId: '',
      //   firstName: 'Odegard',
      //   lastName: '',
      //   shortFirstName: 'Odegard',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 5,
      //   playerId: '',
      //   clubId: '1',
      //   contestantId: '',
      //   firstName: 'Smith',
      //   lastName: 'Rowe',
      //   shortFirstName: 'Smith',
      //   shortLastName: 'Rowe',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 6,
      //   playerId: '',
      //   clubId: '1',
      //   contestantId: '',
      //   firstName: 'Martinelli',
      //   lastName: '',
      //   shortFirstName: 'Martinelli',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 7,
      //   playerId: '',
      //   clubId: '1',
      //   contestantId: '',
      //   firstName: 'Nketiah',
      //   lastName: '',
      //   shortFirstName: 'Nketiah',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 8,
      //   playerId: '',
      //   clubId: '1',
      //   contestantId: '',
      //   firstName: 'zinchenko',
      //   lastName: '',
      //   shortFirstName: 'zinchenko',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Aston Villa
      // {
      //   rewardCode: 9,
      //   playerId: '',
      //   clubId: '2',
      //   contestantId: '',
      //   firstName: 'Ings',
      //   lastName: '',
      //   shortFirstName: 'Ings',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 10,
      //   playerId: '',
      //   clubId: '2',
      //   contestantId: '',
      //   firstName: 'Watkins',
      //   lastName: '',
      //   shortFirstName: 'Watkins',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 11,
      //   playerId: '',
      //   clubId: '2',
      //   contestantId: '',
      //   firstName: 'Cash',
      //   lastName: '',
      //   shortFirstName: 'Cash',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 12,
      //   playerId: '',
      //   clubId: '2',
      //   contestantId: '',
      //   firstName: 'Coutinho',
      //   lastName: '',
      //   shortFirstName: 'Coutinho',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 13,
      //   playerId: '',
      //   clubId: '2',
      //   contestantId: '',
      //   firstName: 'Jacob',
      //   lastName: 'Ramsey',
      //   shortFirstName: 'Jacob',
      //   shortLastName: 'Ramsey',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 14,
      //   playerId: '',
      //   clubId: '2',
      //   contestantId: '',
      //   firstName: 'Buendia',
      //   lastName: '',
      //   shortFirstName: 'Buendia',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Bournemouth
      // {
      //   rewardCode: 15,
      //   playerId: '',
      //   clubId: '4',
      //   contestantId: '',
      //   firstName: 'Billing',
      //   lastName: '',
      //   shortFirstName: 'Billing',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 16,
      //   playerId: '',
      //   clubId: '4',
      //   contestantId: '',
      //   firstName: 'Anthony',
      //   lastName: '',
      //   shortFirstName: 'Anthony',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // brentford
      // {
      //   rewardCode: 17,
      //   playerId: '',
      //   clubId: '5',
      //   contestantId: '',
      //   firstName: 'Jansson',
      //   lastName: '',
      //   shortFirstName: 'Jansson',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 18,
      //   playerId: '',
      //   clubId: '5',
      //   contestantId: '',
      //   firstName: 'toney',
      //   lastName: '',
      //   shortFirstName: 'toney',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 19,
      //   playerId: '',
      //   clubId: '5',
      //   contestantId: '',
      //   firstName: 'mbeumo',
      //   lastName: '',
      //   shortFirstName: 'mbeumo',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 20,
      //   playerId: '',
      //   clubId: '5',
      //   contestantId: '',
      //   firstName: 'Wissa',
      //   lastName: '',
      //   shortFirstName: 'Wissa',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Brighton
      // {
      //   rewardCode: 21,
      //   playerId: '',
      //   clubId: '3',
      //   contestantId: '',
      //   firstName: 'Trossard',
      //   lastName: '',
      //   shortFirstName: 'Trossard',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 22,
      //   playerId: '',
      //   clubId: '3',
      //   contestantId: '',
      //   firstName: 'Alexis',
      //   lastName: 'Macallister',
      //   shortFirstName: 'Alexis',
      //   shortLastName: 'Macallister',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 23,
      //   playerId: '',
      //   clubId: '3',
      //   contestantId: '',
      //   firstName: 'Maupay',
      //   lastName: '',
      //   shortFirstName: 'Maupay',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 24,
      //   playerId: '',
      //   clubId: '3',
      //   contestantId: '',
      //   firstName: 'Welbeck',
      //   lastName: '',
      //   shortFirstName: 'Welbeck',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 25,
      //   playerId: '',
      //   clubId: '3',
      //   contestantId: '',
      //   firstName: 'Gross',
      //   lastName: '',
      //   shortFirstName: 'Gross',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Chelsea
      // {
      //   rewardCode: 26,
      //   playerId: '',
      //   clubId: '5',
      //   contestantId: '',
      //   firstName: 'Sterling',
      //   lastName: '',
      //   shortFirstName: 'Sterling',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 27,
      //   playerId: '',
      //   clubId: '6',
      //   contestantId: '',
      //   firstName: 'Havertz',
      //   lastName: '',
      //   shortFirstName: 'Havertz',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 28,
      //   playerId: '',
      //   clubId: '6',
      //   contestantId: '',
      //   firstName: 'Mount',
      //   lastName: '',
      //   shortFirstName: 'Mount',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 29,
      //   playerId: '',
      //   clubId: '6',
      //   contestantId: '',
      //   firstName: 'Jorginho',
      //   lastName: '',
      //   shortFirstName: 'Jorginho',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 30,
      //   playerId: '',
      //   clubId: '6',
      //   contestantId: '',
      //   firstName: 'James',
      //   lastName: '',
      //   shortFirstName: 'James',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 31,
      //   playerId: '',
      //   clubId: '6',
      //   contestantId: '',
      //   firstName: 'Werner',
      //   lastName: '',
      //   shortFirstName: 'Werner',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 32,
      //   playerId: '',
      //   clubId: '6',
      //   contestantId: '',
      //   firstName: 'ziyech',
      //   lastName: '',
      //   shortFirstName: 'ziyech',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 33,
      //   playerId: '',
      //   clubId: '6',
      //   contestantId: '',
      //   firstName: 'Alonso',
      //   lastName: '',
      //   shortFirstName: 'Alonso',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Crystal Palace
      // {
      //   rewardCode: 34,
      //   playerId: '',
      //   clubId: '7',
      //   contestantId: '',
      //   firstName: 'Zaha',
      //   lastName: '',
      //   shortFirstName: 'Zaha',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 35,
      //   playerId: '',
      //   clubId: '7',
      //   contestantId: '',
      //   firstName: 'Edouard',
      //   lastName: '',
      //   shortFirstName: 'Edouard',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 36,
      //   playerId: '',
      //   clubId: '7',
      //   contestantId: '',
      //   firstName: 'Schlupp',
      //   lastName: '',
      //   shortFirstName: 'Schlupp',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 37,
      //   playerId: '',
      //   clubId: '7',
      //   contestantId: '',
      //   firstName: 'Mateta',
      //   lastName: '',
      //   shortFirstName: 'Mateta',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Everton
      // {
      //   rewardCode: 38,
      //   playerId: '',
      //   clubId: '8',
      //   contestantId: '',
      //   firstName: 'Gray',
      //   lastName: '',
      //   shortFirstName: 'Gray',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 39,
      //   playerId: '',
      //   clubId: '8',
      //   contestantId: '',
      //   firstName: 'Gordon',
      //   lastName: '',
      //   shortFirstName: 'Gordon',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 40,
      //   playerId: '',
      //   clubId: '8',
      //   contestantId: '',
      //   firstName: 'Doucoure',
      //   lastName: '',
      //   shortFirstName: 'Doucoure',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 41,
      //   playerId: '',
      //   clubId: '8',
      //   contestantId: '',
      //   firstName: 'Calvert',
      //   lastName: 'Lewin',
      //   shortFirstName: 'Calvert',
      //   shortLastName: 'Lewin',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // fulham
      // {
      //   rewardCode: 42,
      //   playerId: '',
      //   clubId: '9',
      //   contestantId: '',
      //   firstName: 'Mitrovic',
      //   lastName: '',
      //   shortFirstName: 'Mitrovic',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 43,
      //   playerId: '',
      //   clubId: '9',
      //   contestantId: '',
      //   firstName: 'Wilson',
      //   lastName: '',
      //   shortFirstName: 'Wilson',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // Leeds
      // {
      //   rewardCode: 44,
      //   playerId: '',
      //   clubId: '10',
      //   contestantId: '',
      //   firstName: 'Bamford',
      //   lastName: '',
      //   shortFirstName: 'Bamford',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 45,
      //   playerId: '',
      //   clubId: '10',
      //   contestantId: '',
      //   firstName: 'Rodrigo',
      //   lastName: '',
      //   shortFirstName: 'Rodrigo',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 46,
      //   playerId: '',
      //   clubId: '10',
      //   contestantId: '',
      //   firstName: 'Jack',
      //   lastName: 'Harrison',
      //   shortFirstName: 'Jack',
      //   shortLastName: 'Harrison',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 47,
      //   playerId: '',
      //   clubId: '10',
      //   contestantId: '',
      //   firstName: 'Daniel',
      //   lastName: 'James',
      //   shortFirstName: 'Daniel',
      //   shortLastName: 'James',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Leicester
      // {
      //   rewardCode: 48,
      //   playerId: '',
      //   clubId: '11',
      //   contestantId: '',
      //   firstName: 'Vardy',
      //   lastName: '',
      //   shortFirstName: 'Vardy',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 49,
      //   playerId: '',
      //   clubId: '11',
      //   contestantId: '',
      //   firstName: 'Iheanacho',
      //   lastName: '',
      //   shortFirstName: 'Iheanacho',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 50,
      //   playerId: '',
      //   clubId: '11',
      //   contestantId: '',
      //   firstName: 'Maddison',
      //   lastName: '',
      //   shortFirstName: 'Maddison',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 51,
      //   playerId: '',
      //   clubId: '11',
      //   contestantId: '',
      //   firstName: 'Barnes',
      //   lastName: '',
      //   shortFirstName: 'Barnes',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 52,
      //   playerId: '',
      //   clubId: '11',
      //   contestantId: '',
      //   firstName: 'Tielmans',
      //   lastName: '',
      //   shortFirstName: 'Tielmans',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 53,
      //   playerId: '',
      //   clubId: '11',
      //   contestantId: '',
      //   firstName: 'Daka',
      //   lastName: '',
      //   shortFirstName: 'Daka',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Liverpool
      // {
      //   rewardCode: 54,
      //   playerId: '',
      //   clubId: '12',
      //   contestantId: '',
      //   firstName: 'Trent',
      //   lastName: 'Alexander Arnold',
      //   shortFirstName: 'Trent',
      //   shortLastName: 'Alexander Arnold',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 55,
      //   playerId: '',
      //   clubId: '12',
      //   contestantId: '',
      //   firstName: 'Robertson',
      //   lastName: '',
      //   shortFirstName: 'Robertson',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 56,
      //   playerId: '',
      //   clubId: '12',
      //   contestantId: '',
      //   firstName: 'Salah',
      //   lastName: '',
      //   shortFirstName: 'Salah',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 57,
      //   playerId: '',
      //   clubId: '12',
      //   contestantId: '',
      //   firstName: 'Jota',
      //   lastName: '',
      //   shortFirstName: 'Jota',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 58,
      //   playerId: '',
      //   clubId: '12',
      //   contestantId: '',
      //   firstName: 'Darwin',
      //   lastName: 'Nunez',
      //   shortFirstName: 'Darwin',
      //   shortLastName: 'Nunez',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 59,
      //   playerId: '',
      //   clubId: '12',
      //   contestantId: '',
      //   firstName: 'Fabinho',
      //   lastName: '',
      //   shortFirstName: 'Fabinho',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 60,
      //   playerId: '',
      //   clubId: '12',
      //   contestantId: '',
      //   firstName: 'Firminho',
      //   lastName: '',
      //   shortFirstName: 'Firminho',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 61,
      //   playerId: '',
      //   clubId: '12',
      //   contestantId: '',
      //   firstName: 'Luis',
      //   lastName: 'Diaz',
      //   shortFirstName: 'Luis',
      //   shortLastName: 'Diaz',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Manchester City
      // {
      //   rewardCode: 62,
      //   playerId: '',
      //   clubId: '13',
      //   contestantId: '',
      //   firstName: 'Grealish',
      //   lastName: '',
      //   shortFirstName: 'Grealish',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 63,
      //   playerId: '',
      //   clubId: '13',
      //   contestantId: '',
      //   firstName: 'Diaz',
      //   lastName: '',
      //   shortFirstName: 'Diaz',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 64,
      //   playerId: '',
      //   clubId: '13',
      //   contestantId: '',
      //   firstName: 'Haaland',
      //   lastName: '',
      //   shortFirstName: 'Haaland',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 65,
      //   playerId: '',
      //   clubId: '13',
      //   contestantId: '',
      //   firstName: 'De',
      //   lastName: 'Bruyne',
      //   shortFirstName: 'De',
      //   shortLastName: 'Bruyne',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 66,
      //   playerId: '',
      //   clubId: '13',
      //   contestantId: '',
      //   firstName: 'Bernardo',
      //   lastName: 'Silva',
      //   shortFirstName: 'Bernardo',
      //   shortLastName: 'Silva',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 67,
      //   playerId: '',
      //   clubId: '13',
      //   contestantId: '',
      //   firstName: 'Phil',
      //   lastName: 'Foden',
      //   shortFirstName: 'Phil',
      //   shortLastName: 'Foden',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 68,
      //   playerId: '',
      //   clubId: '13',
      //   contestantId: '',
      //   firstName: 'Mahrez',
      //   lastName: '',
      //   shortFirstName: 'Mahrez',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 69,
      //   playerId: '',
      //   clubId: '13',
      //   contestantId: '',
      //   firstName: 'Gündogan',
      //   lastName: '',
      //   shortFirstName: 'Gündogan',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Manchester United
      // {
      //   rewardCode: 70,
      //   playerId: '',
      //   clubId: '14',
      //   contestantId: '',
      //   firstName: 'Bruno',
      //   lastName: 'Fernandes',
      //   shortFirstName: 'Bruno',
      //   shortLastName: 'Fernandes',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 71,
      //   playerId: '',
      //   clubId: '14',
      //   contestantId: '',
      //   firstName: 'Fred',
      //   lastName: '',
      //   shortFirstName: 'Fred',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 72,
      //   playerId: '',
      //   clubId: '14',
      //   contestantId: '',
      //   firstName: 'Jadon',
      //   lastName: 'Sancho',
      //   shortFirstName: 'Jadon',
      //   shortLastName: 'Sancho',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 73,
      //   playerId: '',
      //   clubId: '14',
      //   contestantId: '',
      //   firstName: 'Ronaldo',
      //   lastName: '',
      //   shortFirstName: 'Ronaldo',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 74,
      //   playerId: '',
      //   clubId: '14',
      //   contestantId: '',
      //   firstName: 'Rashford',
      //   lastName: '',
      //   shortFirstName: 'Rashford',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 75,
      //   playerId: '',
      //   clubId: '14',
      //   contestantId: '',
      //   firstName: 'Eriksen',
      //   lastName: '',
      //   shortFirstName: 'Eriksen',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // Newcastle
      // {
      //   rewardCode: 76,
      //   playerId: '',
      //   clubId: '15',
      //   contestantId: '',
      //   firstName: 'Saint',
      //   lastName: 'Maximin',
      //   shortFirstName: 'Saint',
      //   shortLastName: 'Maximin',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 77,
      //   playerId: '',
      //   clubId: '15',
      //   contestantId: '',
      //   firstName: 'Wood',
      //   lastName: '',
      //   shortFirstName: 'Wood',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 78,
      //   playerId: '',
      //   clubId: '15',
      //   contestantId: '',
      //   firstName: 'Wilson',
      //   lastName: '',
      //   shortFirstName: 'Wilson',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 79,
      //   playerId: '',
      //   clubId: '15',
      //   contestantId: '',
      //   firstName: 'Joelinton',
      //   lastName: '',
      //   shortFirstName: 'Joelinton',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Nottingham Forest
      // {
      //   rewardCode: 80,
      //   playerId: '',
      //   clubId: '16',
      //   contestantId: '',
      //   firstName: 'Johnson',
      //   lastName: '',
      //   shortFirstName: 'Johnson',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 81,
      //   playerId: '',
      //   clubId: '16',
      //   contestantId: '',
      //   firstName: 'Lingard',
      //   lastName: '',
      //   shortFirstName: 'Lingard',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // southampton
      // {
      //   rewardCode: 82,
      //   playerId: '',
      //   clubId: '17',
      //   contestantId: '',
      //   firstName: 'Adams',
      //   lastName: '',
      //   shortFirstName: 'Adams',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 83,
      //   playerId: '',
      //   clubId: '17',
      //   contestantId: '',
      //   firstName: 'Ward',
      //   lastName: 'Prowse',
      //   shortFirstName: 'Ward',
      //   shortLastName: 'Prowse',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 84,
      //   playerId: '',
      //   clubId: '17',
      //   contestantId: '',
      //   firstName: 'Elyounoussi',
      //   lastName: '',
      //   shortFirstName: 'Elyounoussi',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 85,
      //   playerId: '',
      //   clubId: '17',
      //   contestantId: '',
      //   firstName: 'Armstrong',
      //   lastName: '',
      //   shortFirstName: 'Armstrong',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Tottenham
      // {
      //   rewardCode: 86,
      //   playerId: '',
      //   clubId: '18',
      //   contestantId: '',
      //   firstName: 'Kane',
      //   lastName: '',
      //   shortFirstName: 'Kane',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 87,
      //   playerId: '',
      //   clubId: '18',
      //   contestantId: '',
      //   firstName: 'Song',
      //   lastName: '',
      //   shortFirstName: 'Song',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 88,
      //   playerId: '',
      //   clubId: '18',
      //   contestantId: '',
      //   firstName: 'Richarlison',
      //   lastName: '',
      //   shortFirstName: 'Richarlison',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 89,
      //   playerId: '',
      //   clubId: '18',
      //   contestantId: '',
      //   firstName: 'Kulusevski',
      //   lastName: '',
      //   shortFirstName: 'Kulusevski',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 90,
      //   playerId: '',
      //   clubId: '18',
      //   contestantId: '',
      //   firstName: 'Moura',
      //   lastName: '',
      //   shortFirstName: 'Moura',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 91,
      //   playerId: '',
      //   clubId: '18',
      //   contestantId: '',
      //   firstName: 'Reguilon',
      //   lastName: '',
      //   shortFirstName: 'Reguilon',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // West Ham
      // {
      //   rewardCode: 92,
      //   playerId: '',
      //   clubId: '19',
      //   contestantId: '',
      //   firstName: 'Creswell',
      //   lastName: '',
      //   shortFirstName: 'Creswell',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 93,
      //   playerId: '',
      //   clubId: '19',
      //   contestantId: '',
      //   firstName: 'Antonio',
      //   lastName: '',
      //   shortFirstName: 'Antonio',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 94,
      //   playerId: '',
      //   clubId: '19',
      //   contestantId: '',
      //   firstName: 'Bowen',
      //   lastName: '',
      //   shortFirstName: 'Bowen',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 95,
      //   playerId: '',
      //   clubId: '19',
      //   contestantId: '',
      //   firstName: 'Benrahma',
      //   lastName: '',
      //   shortFirstName: 'Benrahma',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 96,
      //   playerId: '',
      //   clubId: '19',
      //   contestantId: '',
      //   firstName: 'Fornals',
      //   lastName: '',
      //   shortFirstName: 'Fornals',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // // Wolves
      // {
      //   rewardCode: 97,
      //   playerId: '',
      //   clubId: '20',
      //   contestantId: '',
      //   firstName: 'Jiminez',
      //   lastName: '',
      //   shortFirstName: 'Jiminez',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 98,
      //   playerId: '',
      //   clubId: '20',
      //   contestantId: '',
      //   firstName: 'Moutinho',
      //   lastName: '',
      //   shortFirstName: 'Moutinho',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 100,
      //   playerId: '',
      //   clubId: '20',
      //   contestantId: '',
      //   firstName: 'Hwang',
      //   lastName: '',
      //   shortFirstName: 'Hwang',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
      // {
      //   rewardCode: 99,
      //   playerId: '',
      //   clubId: '20',
      //   contestantId: '',
      //   firstName: 'Neves',
      //   lastName: '',
      //   shortFirstName: 'Neves',
      //   shortLastName: '',
      //   shirtPlayer: '',
      //   matchName: '',
      //   shirtNumber: '0',
      //   position: '',
      //   positionSide: '',
      //   formationPlace: '',
      //   touch: 0,
      //   type: 'TIER1',
      // },
    ];

    const queryRunner = getConnection().createQueryRunner();

    await queryRunner.connect();
    await queryRunner.startTransaction();
    try {
      players.forEach(async (item) => {
        const club = await this.clubRepository.findOne({
          where: { id: item.clubId },
        });
        item.club = club;
        const player = this.playerRepository.create(item);
        await this.playerRepository.save(player);
      });

      await queryRunner.commitTransaction();
    } catch (error) {
      // since we have errors lets rollback the changes we made
      await queryRunner.rollbackTransaction();
    } finally {
      // you need to release a queryRunner which was manually instantiated
      await queryRunner.release();
    }

    return this.playerRepository.find();
  }
}
